language: php

php:
  - 5.4
  - 5.5
  - 5.6

matrix:
  allow_failures:
    - php: 5.6

before_script:
  - composer self-update
  - composer update --prefer-source --dev

script:
  - mkdir -p build/logs
  - vendor/bin/phpunit --coverage-clover build/logs/clover.xml
  - vendor/bin/phpcs --standard=PSR2 src/ test/

after_script:
  - php vendor/bin/coveralls
  - vendor/bin/phpmd src/ text cleancode,codesize,controversial,design,naming,unusedcode
