language: php

php:
  - 7.0
  - 7.1

matrix:
  fast_finish: true

before_script:
  - composer install --prefer-dist

script:
  - composer test
  - composer style

after_script:
  - composer check
  - composer metrics
