language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm

matrix:
  fast_finish: true
  allow_failures:
    - php: hhvm

before_script:
  - composer self-update
  - composer update --prefer-source --dev

script:
  - mkdir -p build/logs
  - vendor/bin/phpunit --coverage-clover build/logs/clover.xml
  - vendor/bin/phpcs --standard=PSR2 src/ test/

after_script:
  - sh .travis.coverage.sh
  - vendor/bin/phpmd src/ text cleancode,codesize,controversial,design,naming,unusedcode
